import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to copy files to build directory
const copyPlugin = {
	name: 'copy-plugin',
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				const buildDir = 'build/ai-copilot';

				// Create build directory if it doesn't exist
				mkdirSync(buildDir, { recursive: true });

				// Copy necessary files
				copyFileSync('main.js', join(buildDir, 'main.js'));
				copyFileSync('manifest.json', join(buildDir, 'manifest.json'));
				copyFileSync('styles.css', join(buildDir, 'styles.css'));

				console.log(`✓ Plugin files copied to ${buildDir}/`);
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
